local checkzone = require('named-conf.checkzone')
local zonefile = require('named-conf.zonefile')
local detect = require('named-conf.detect')

describe('checkzone.parse_output', function()
  it('parses plain file:line: message lines', function()
    local out = '/etc/bind/db.example:12: unknown RR type \'AAAAA\'\n'
    local parsed = checkzone.parse_output(out)
    assert.equals(1, #parsed)
    assert.equals('/etc/bind/db.example', parsed[1].file)
    assert.equals(12, parsed[1].lnum)
  end)

  it('strips the routine-name prefix BIND puts before the path', function()
    local out = 'dns_rdata_fromtext: /etc/bind/db.example:5: near \'bad\': not a valid number\n'
    local parsed = checkzone.parse_output(out)
    assert.equals(1, #parsed)
    assert.equals('/etc/bind/db.example', parsed[1].file)
    assert.equals(5, parsed[1].lnum)
    assert.equals("near 'bad': not a valid number", parsed[1].text)
  end)

  it('keeps summary lines without file:line as context', function()
    local out = 'zone example.com/IN: loaded serial 2024010101\n'
    local parsed = checkzone.parse_output(out)
    assert.equals(1, #parsed)
    assert.is_nil(parsed[1].file)
  end)
end)

describe('checkzone.origin_from_name', function()
  it('derives from db.<zone> names', function()
    assert.equals('example.com', checkzone.origin_from_name('/etc/bind/db.example.com'))
  end)
  it('derives from <zone>.zone and <zone>.db names', function()
    assert.equals('example.com', checkzone.origin_from_name('example.com.zone'))
    assert.equals('example.com', checkzone.origin_from_name('zones/example.com.db'))
  end)
  it('accepts a bare dotted zone name', function()
    assert.equals('example.com', checkzone.origin_from_name('example.com'))
  end)
  it('handles signed zones', function()
    assert.equals('example.com', checkzone.origin_from_name('db.example.com.signed'))
  end)
  it('rejects extensionless single labels', function()
    assert.is_nil(checkzone.origin_from_name('hosts'))
    assert.is_nil(checkzone.origin_from_name(''))
  end)
end)

describe('zonefile.lookup', function()
  it('resolves RR types case-insensitively', function()
    local entry, name = zonefile.lookup('soa')
    assert.is_table(entry)
    assert.equals('SOA', name)
    assert.is_truthy(entry.summary)
  end)
  it('resolves $-directives and @', function()
    assert.is_table((zonefile.lookup('$TTL')))
    assert.is_table((zonefile.lookup('@')))
  end)
  it('returns nil for unknown tokens', function()
    assert.is_nil((zonefile.lookup('example')))
  end)
end)

describe('zonefile._word_at', function()
  it('grabs directives and record types', function()
    local line = '$TTL 3600'
    assert.equals('$TTL', zonefile._word_at(line, 0))
    local rr = 'www  IN  A  192.0.2.10'
    assert.equals('A', zonefile._word_at(rr, 9))
  end)
end)

describe('detect.dialect_for (zone)', function()
  it('classifies zone data files', function()
    assert.equals('zone', detect.dialect_for('db.example.com', nil))
    assert.equals('zone', detect.dialect_for('example.com.zone', nil))
    assert.equals('zone', detect.dialect_for('anything', 'bindzone'))
  end)
  it('leaves named.conf and rndc.conf alone', function()
    assert.equals('named', detect.dialect_for('named.conf', 'named'))
    assert.equals('rndc', detect.dialect_for('rndc.conf', 'named'))
  end)
end)
